### ISSUE TITLE
Error when communicating with the native messaging host

### ISSUE THREAD

**Issue by danbugs** [guest271314/native-messaging-webassembly#1]
This refers to the issue brought up here: https://github.com/WebAssembly/wasi-messaging/issues/4#issuecomment-1493406734.

I've followed all relevant steps:

(2) Download and save `wasmtime` executable to the extension directory:
![image](https://user-images.githubusercontent.com/39843321/229616510-2e8a6a0f-3e51-4132-b714-afa2346f705f.png)

(8) Open `nm_c_wasm.json` in a text editor, set `"path"` to absolute path of `nm_c_wasm.sh` or `nm_c_wat.sh` and `chrome-extension://<ID>/` using ID from 7 in `"allowed_origins"` array.
![image](https://user-images.githubusercontent.com/39843321/229616942-99aec114-b2ab-4641-a41d-56c5ac266a86.png)

```json
{
  "name": "nm_c_wasm",
  "description": "WebAssembly Native Messaging host",
  "path": "/Users/danbugs/repos/native-messaging-webassembly/nm_c_wat.sh",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://cgklijjiekmgnpkmjckcalhmckkoloki/"]
}
```

(9) Copy the file to Chrome or Chromium configuration folder, e.g., Chromium on \*nix `~/.config/chromium/NativeMessagingHosts`; Chrome dev channel on \*nix `~/.config/google-chrome-unstable/NativeMessagingHosts`.

![image](https://user-images.githubusercontent.com/39843321/229617442-a9daaad8-6b69-4aeb-8684-9187e961f4fe.png)

(10) Make sure `*.sh` files are executable executable; for WAT embedded in ``nm_c_wat.sh`` we use `kill_wasmtime.sh` to terminate `wasmtime` using polling of `nm_c_wat.sh` because process substitution keeps `wasmtime` running after the Native Messaging host is disconnected and exits.
![image](https://user-images.githubusercontent.com/39843321/229617629-c20940e9-6ebb-4f80-83c9-4facf5b2255b.png)

PS I'm on MacOS, so my extensions dir is different from yours, I referred to this to find the proper directory: https://stackoverflow.com/questions/14543896/where-does-chrome-store-extensions

**Comment by guest271314** [comment]
Does MacOS have `env` in `/usr/bin` or `bash` is `/bin`?

Try modifying `nm_c_wasm.sh` to

```
#!wasmtime nm_c.wasm
```

and substituting that executable for `nm_c_wat.sh` in `"path"` in `nm_c_wasm.json`.

**Comment by guest271314** [comment]
> PS I'm on MacOS

Looks like Bash is not the default shell on MacOS https://dev.to/bphogan/use-modern-bash-shell-on-macos-22a6. 

Shebang `nm_c_wat.sh` is `#!/bin/bash`.

**Comment by danbugs** [comment]
> Does MacOS have env in /usr/bin or bash is /bin?

MacOS does have `/bin/bash`.

> Try modifying `nm_c_wasm.sh` to
> ```
> #!wasmtime nm_c.wasm
> ```

I might be misunderstanding, but that's already the content of `nm_c_wasm.sh`: https://github.com/guest271314/native-messaging-webassembly/blob/38f4a164c6fab99ab95e041f31f6a270409d3e36/nm_c_wasm.sh#L1

> and substituting that executable for `nm_c_wat.sh` in `"path"` in `nm_c_wasm.json`.

The reason I used `nm_c_wat.sh` instead of `nm_c_wasm.sh` is because, when using `nm_c_wasm.sh`, I was getting the following error: https://github.com/NativeMessaging/Documentation/blob/06e2e75a1f3cab327c25b02406e6c88fc034a1b4/Chrome/Errors.md#failed-to-start-native-messaging-host

That said, upon retry, it seems to work: 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/39843321/230178507-e697ba9a-adde-41fd-bacd-905711303dab.png">

~so I'll close this issue. Thank you for the support.

**Comment by guest271314** [comment]
@danbugs Note, `nm_c_wasm.sh` does not exit when Chromium exits. AFAICT that behaviour is specific to `wasmtime`; C, C++, Python, JavaScript (QuickJS; txiki.js; Node.js; Deno) Native Messaging hosts do not exhibit that behavior. That is why I created `nm_c_wat.sh` which terminates the script from the script:


https://github.com/guest271314/native-messaging-webassembly/blob/38f4a164c6fab99ab95e041f31f6a270409d3e36/nm_c_wat.sh#L6361-L6362
